In [2]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression, LogisticRegressionCV

In [3]:
data = pd.read_csv('../input/oranges-vs-grapefruit/citrus.csv')

In [4]:
data

            name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10000 non-null  object
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64
 4   green     10000 non-null  int64
 5   blue      10000 non-null  int64
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB

In [6]:
data['name'].value_counts()

orange        5000
grapefruit    5000
Name: name, dtype: int64

In [7]:
label_mapping = {'orange': 0, 'grapefruit': 1}

data['name'] = data['name'].replace(label_mapping)

In [8]:
data

      name  diameter  weight  red  green  blue
0        0      2.96   86.76  172     85     2
1        0      3.91   88.05  166     78     3
2        0      4.42   95.17  156     81     2
3        0      4.47   95.60  163     81     4
4        0      4.48   95.76  161     72     9
...    ...       ...     ...  ...    ...   ...
9995     1     15.35  253.89  149     77    20
9996     1     15.41  254.67  148     68     7
9997     1     15.59  256.50  168     82    20
9998     1     15.92  260.14  142     72    11
9999     1     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [9]:
y = data['name']
X = data.drop('name', axis=1)

In [10]:
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=20)

In [12]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

lr_acc = lr_model.score(X_test, y_test)

print("Accuracy: {:.4f}".format(lr_acc))

Accuracy: 0.9390

In [13]:
cv_model = LogisticRegressionCV()
cv_model.fit(X_train, y_train)

cv_acc = cv_model.score(X_test, y_test)

print("Accuracy: {:.4f}".format(cv_acc))

Accuracy: 0.9597